# Site settings
title: 何患架上药生尘
email: QYD720@gmail.com
url: https://QYD720.github.io
description: "我是一个没有感情的二傻子。"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title:Weibo
    url:  
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: 
# Build settings
markdown: kramdown
permalink: pretty
